name: 部署服务
on:
  push:
    branch:
      - main
    tags: "v*"
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/actions:${{github.ref_name}}
      - name: Push the Docker image
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
          docker push ${{secrets.DOCKER_USERNAME}}/actions:${{github.ref_name}}
          curl ifconfig.me
      - name: 部署镜像
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker rm -f actions
            docker rmi -f $(docker images -aq --filter reference='*/actions:v*.*.*')
            docker pull ${{secrets.DOCKER_USERNAME}}/actions:${{github.ref_name}}
            docker run -d --name actions -p "8080:8080" ${{secrets.DOCKER_USERNAME}}/actions:${{github.ref_name}}
            curl ifconfig.me