name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - ^[1-9]\d*(\.[1-9]\d*)*$
  pull_request:
    branches: [ "main" ]
    tags:
      - ^[1-9]\d*(\.[1-9]\d*)*$

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zouyu99/actions:1.0.0
    - name: Pull the Docker image
      run: |
        docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        docker push zouyu99/actions:1.0.0

