name: get tags
on:
  - push
jobs:
  github-get-tags:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 124.22.167.219
          username: ubuntu
          password: @ZouYu999
          port: 22
          script: |
            cd ~/
            ls